/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.w3c.dom.events.Event;

/**
 *
 * @author bruno.schneider
 */
public class Application extends javax.swing.JFrame {

    Logic lg = new Logic();
    Alvo Alvo = new Alvo();
    Atirador atirador = new Atirador();
    int positionX = 0;
    int positionY = 0;
    //int h = 1;
    int j = 1;
    String fase = "fase";

    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        mudarCenario();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        imagemFundo2 = new Project.imagemFundo();
        painel = new javax.swing.JPanel();
        imgF = new Project.imagemFundo();

        alvo = new javax.swing.JLabel();
        iconSkull = new javax.swing.JLabel();
        numberSkull = new javax.swing.JLabel();
        hit = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout imagemFundo2Layout = new javax.swing.GroupLayout(imagemFundo2);
        imagemFundo2.setLayout(imagemFundo2Layout);
        imagemFundo2Layout.setHorizontalGroup(
            imagemFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imagemFundo2Layout.setVerticalGroup(
            imagemFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("F"); // NOI18N
        setUndecorated(true);

        painel.setBackground(new java.awt.Color(204, 204, 204));
        painel.setForeground(new java.awt.Color(102, 102, 255));
        painel.setPreferredSize(new java.awt.Dimension(500, 500));

        imgF.setImg(new ImageIcon("src\\imagens\\planeta.jpg"));
        imgF.setPreferredSize(new java.awt.Dimension(500, 500));
        imgF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgFMouseClicked(evt);
            }
        });

        alvo.setBackground(new java.awt.Color(0, 0, 0));
        alvo.setForeground(new java.awt.Color(255, 51, 51));
        alvo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icons8-predator-40 (1).png"))); // NOI18N
        alvo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alvoMouseClicked(evt);
            }
        });

        iconSkull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-skull-48.png"))); // NOI18N

        numberSkull.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        numberSkull.setForeground(new java.awt.Color(255, 0, 51));
        numberSkull.setText("Deaths");

        hit.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        hit.setForeground(new java.awt.Color(255, 0, 0));
        hit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hit.png"))); // NOI18N
        hit.setText("Hits");

        javax.swing.GroupLayout imgFLayout = new javax.swing.GroupLayout(imgF);
        imgF.setLayout(imgFLayout);
        imgFLayout.setHorizontalGroup(
            imgFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgFLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconSkull)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberSkull)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(hit)
                .addGap(40, 40, 40))
            .addGroup(imgFLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(alvo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imgFLayout.setVerticalGroup(
            imgFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imgFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imgFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hit)
                        .addComponent(numberSkull))
                    .addComponent(iconSkull))
                .addGap(172, 172, 172)
                .addComponent(alvo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alvoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alvoMouseClicked

        funcionHit();
        hitAlvo();

        numberSkull.setText(String.valueOf(Alvo.getDeath()));
        hit.setText(String.valueOf(atirador.getNumberShot()));


    }//GEN-LAST:event_alvoMouseClicked

    private void imgFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFMouseClicked
        funcionHit();
        hit.setText(String.valueOf(atirador.getNumberShot()));

    }//GEN-LAST:event_imgFMouseClicked

    public int mudarPocitionX() {
        positionX = lg.returnPositonHorizontal();
        return positionX;
    }

    public int mudarPocitionY() {
        int positionY = lg.returnPositonVertical();
        return positionY;
    }

    public void hitAlvo() {
        Alvo.setDeath(+1);
    }

    public void funcionHit() {
        atirador.setNumberShot(+1);
    }

    public void andar() {

        new Thread() {
            public void run() {

                int x = positionX;
                int y = positionY;
                int z = 0;

                while (true) {

                    if (z == 1) {
                        x++;
                        y--;

                    } else if (z == 0) {
                        x--;
                        y++;

                    }
                    if (x > getWidth() || x >getHeight()) {
                        x = mudarPocitionX();
                        y = mudarPocitionY();
                        if (z == 0) {
                            z++;
                        } else if (z == 1) {
                            z--;
                        }
                    } else if (x <= 0 || y <= 0) {

                        x = mudarPocitionX();
                        y = mudarPocitionY();
                        if (z == 0) {
                            z++;
                        } else if (z == 1) {
                            z--;
                        }
                    }

                    alvo.setLocation(x, y);
                    try {

                        sleep(10);

                    } catch (Exception e) {
                        System.out.println("deu ruim");
                    }
                }
            }
        }.start();
    }

    public void mudarCenario() {
        new Thread() {
            public void run() {
                andar();
                int h = 1;
                String f = "fase";
                String p = "planeta";
                while (true) {

                    for (int i = 1; i < 10; ++i) {
                        try {
                        if( i <= 7){
                            imgF.setImg(new ImageIcon(getClass().getResource("/imagens/"+p + i + ".jpg")));
                            sleep(400);
                            imgF.repaint();
                        }if(i > 7){
                            imgF.setImg(new ImageIcon(getClass().getResource("/imagens/"+p + i + ".jpg")));
                            sleep(1000);
                            imgF.repaint();
                        }
                        
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                        System.out.println("hello" );
                        
                        // imagemFundo1.imageUpdate(img, NORMAL, imagemFundo1.getX();, h, h, h);
                    }
                }
            }.start();
     }

    

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alvo;
    private javax.swing.JLabel hit;
    private javax.swing.JLabel iconSkull;
    private Project.imagemFundo imagemFundo2;
    private Project.imagemFundo imgF;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numberSkull;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}

